-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.allergens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  severity character varying,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT allergens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid,
  source_table text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  action text NOT NULL,
  summary text,
  notes text,
  before_data jsonb,
  after_data jsonb,
  actor_user_id uuid,
  actor_name text,
  actor_role text,
  actor_care_home_id uuid,
  actor_org text,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT audit_logs_actor_care_home_id_fkey FOREIGN KEY (actor_care_home_id) REFERENCES public.care_homes(id)
);
CREATE TABLE public.care_homes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text NOT NULL,
  address text NOT NULL,
  postcode text,
  phone text,
  email text,
  manager_name text,
  capacity integer NOT NULL DEFAULT 0,
  current_residents integer NOT NULL DEFAULT 0,
  status text DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Inactive'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT care_homes_pkey PRIMARY KEY (id),
  CONSTRAINT care_homes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.community_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  parent_id uuid,
  author_id uuid NOT NULL,
  body text NOT NULL,
  upvotes integer DEFAULT 0,
  downvotes integer DEFAULT 0,
  is_edited boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT community_comments_pkey PRIMARY KEY (id),
  CONSTRAINT community_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.community_posts(id),
  CONSTRAINT community_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.community_comments(id),
  CONSTRAINT community_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.community_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['like'::text, 'dislike'::text, 'upvote'::text, 'downvote'::text, 'comment'::text, 'reply'::text])),
  post_id uuid,
  comment_id uuid,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT community_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT community_notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id),
  CONSTRAINT community_notifications_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id),
  CONSTRAINT community_notifications_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.community_posts(id),
  CONSTRAINT community_notifications_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.community_comments(id)
);
CREATE TABLE public.community_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_id uuid NOT NULL,
  organization_id uuid,
  title text NOT NULL,
  body text,
  flair text DEFAULT 'Discussion'::text,
  media_urls jsonb DEFAULT '[]'::jsonb,
  upvotes integer DEFAULT 0,
  downvotes integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  is_pinned boolean DEFAULT false,
  is_edited boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  poll_data jsonb,
  CONSTRAINT community_posts_pkey PRIMARY KEY (id),
  CONSTRAINT community_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT community_posts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.community_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  post_id uuid,
  comment_id uuid,
  vote smallint NOT NULL CHECK (vote = ANY (ARRAY['-1'::integer, 1])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT community_votes_pkey PRIMARY KEY (id),
  CONSTRAINT community_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT community_votes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.community_posts(id),
  CONSTRAINT community_votes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.community_comments(id)
);
CREATE TABLE public.compliance_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  severity character varying,
  title character varying NOT NULL,
  description text,
  facility_id uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT compliance_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dietary_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT dietary_requirements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid,
  facility_id uuid NOT NULL,
  item character varying NOT NULL,
  category character varying,
  amount numeric NOT NULL,
  supplier character varying,
  date date NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT expenses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ingredient_care_home_price_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ingredient_id uuid NOT NULL,
  care_home_id uuid NOT NULL,
  price numeric NOT NULL,
  price_unit text DEFAULT 'kg'::text,
  effective_from timestamp with time zone NOT NULL DEFAULT now(),
  effective_to timestamp with time zone,
  reason text,
  changed_by_user_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ingredient_care_home_price_history_pkey PRIMARY KEY (id),
  CONSTRAINT ingredient_care_home_price_history_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id),
  CONSTRAINT ingredient_care_home_price_history_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id)
);
CREATE TABLE public.ingredient_care_home_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ingredient_id uuid NOT NULL,
  care_home_id uuid NOT NULL,
  price numeric NOT NULL,
  price_unit text DEFAULT 'kg'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ingredient_care_home_prices_pkey PRIMARY KEY (id),
  CONSTRAINT ingredient_care_home_prices_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id),
  CONSTRAINT ingredient_care_home_prices_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id)
);
CREATE TABLE public.ingredient_price_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ingredient_id uuid NOT NULL,
  price numeric NOT NULL,
  price_unit text DEFAULT 'kg'::text,
  effective_from timestamp with time zone NOT NULL DEFAULT now(),
  effective_to timestamp with time zone,
  reason text,
  changed_by_user_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ingredient_price_history_pkey PRIMARY KEY (id),
  CONSTRAINT ingredient_price_history_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id)
);
CREATE TABLE public.ingredient_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ingredient_id uuid NOT NULL,
  quantity numeric NOT NULL,
  quantity_unit text NOT NULL DEFAULT 'kg'::text,
  unit_price numeric NOT NULL,
  total_cost numeric NOT NULL,
  supplier_name text,
  supplier_location text,
  purchase_date date NOT NULL DEFAULT CURRENT_DATE,
  receipt_reference text,
  notes text,
  care_home_id uuid,
  organization_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ingredient_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT ingredient_purchases_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id),
  CONSTRAINT ingredient_purchases_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT ingredient_purchases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT ingredient_purchases_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ingredients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text DEFAULT 'Other'::text CHECK (category = ANY (ARRAY['Proteins'::text, 'Dairy'::text, 'Grains'::text, 'Vegetables'::text, 'Fruits'::text, 'Oils & Fats'::text, 'Spices & Herbs'::text, 'Condiments'::text, 'Beverages'::text, 'Other'::text])),
  allergens jsonb NOT NULL DEFAULT '[]'::jsonb,
  nutritional_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  current_price numeric DEFAULT 0,
  price_unit text DEFAULT 'kg'::text,
  image_url text,
  notes text,
  is_active boolean DEFAULT true,
  organization_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ingredients_pkey PRIMARY KEY (id),
  CONSTRAINT ingredients_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT ingredients_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.meal_allergens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid NOT NULL,
  allergen_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT meal_allergens_pkey PRIMARY KEY (id),
  CONSTRAINT meal_allergens_allergen_id_fkey FOREIGN KEY (allergen_id) REFERENCES public.allergens(id)
);
CREATE TABLE public.meal_cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  cycle_name text NOT NULL DEFAULT 'Standard Cycle'::text,
  cycle_length_weeks integer NOT NULL DEFAULT 3,
  start_date date NOT NULL,
  end_date date,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  change_reason text,
  week_offset integer NOT NULL DEFAULT 0,
  CONSTRAINT meal_cycles_pkey PRIMARY KEY (id),
  CONSTRAINT meal_cycles_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meal_cycles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.meal_delivery_alternates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  date date NOT NULL,
  meal_type text NOT NULL,
  resident_id uuid,
  alternate_meal_id uuid NOT NULL,
  alternate_side_meal_id uuid,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resident_count integer DEFAULT 0,
  alternate_side_meal_ids jsonb,
  alternate_dessert_ids jsonb,
  alternate_dessert_id uuid,
  unit_cost numeric,
  subtotal numeric,
  alt_base_unit_cost numeric,
  alt_sides_unit_cost numeric,
  alt_desserts_unit_cost numeric,
  components jsonb,
  CONSTRAINT meal_delivery_alternates_pkey PRIMARY KEY (id),
  CONSTRAINT meal_delivery_alternates_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meal_delivery_alternates_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT meal_delivery_alternates_alternate_meal_id_fkey FOREIGN KEY (alternate_meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_delivery_alternates_alternate_side_meal_id_fkey FOREIGN KEY (alternate_side_meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_delivery_alternates_alternate_dessert_id_fkey FOREIGN KEY (alternate_dessert_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meal_delivery_extras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  date date NOT NULL,
  meal_type text NOT NULL,
  extra_meal_id uuid NOT NULL,
  extra_meal_kind text NOT NULL DEFAULT 'meal'::text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  reason text,
  unit_cost numeric DEFAULT 0,
  subtotal numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_delivery_extras_pkey PRIMARY KEY (id),
  CONSTRAINT meal_delivery_extras_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meal_delivery_extras_extra_meal_id_fkey FOREIGN KEY (extra_meal_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meal_delivery_status (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  date date NOT NULL,
  meal_type text NOT NULL,
  delivered boolean DEFAULT false,
  served_count integer DEFAULT 0,
  changed_for_all boolean DEFAULT false,
  new_main_meal_id uuid,
  new_side_meal_id uuid,
  change_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_by uuid,
  confirmed_at timestamp with time zone,
  confirmed_by_name text,
  edited_at timestamp with time zone,
  edit_reason text,
  allow_second_edit boolean DEFAULT false,
  second_edit_allowed_by uuid,
  second_edit_allowed_at timestamp with time zone,
  second_edit_allowed_reason text,
  second_edited_at timestamp with time zone,
  second_edit_reason text,
  second_edit_allowed_by_name text,
  second_edited_by uuid,
  second_edited_by_name text,
  new_side_meal_ids jsonb,
  new_dessert_ids jsonb,
  new_dessert_meal_id uuid,
  main_unit_cost numeric,
  main_subtotal numeric,
  alternates_total numeric,
  specials_total numeric,
  grand_total numeric,
  main_base_unit_cost numeric,
  main_sides_unit_cost numeric,
  main_desserts_unit_cost numeric,
  main_components jsonb,
  alternates_details jsonb,
  specials_details jsonb,
  side_meal_counts jsonb,
  dessert_counts jsonb,
  extras_details jsonb,
  extras_total numeric DEFAULT 0,
  CONSTRAINT meal_delivery_status_pkey PRIMARY KEY (id),
  CONSTRAINT meal_delivery_status_new_main_meal_id_fkey FOREIGN KEY (new_main_meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_delivery_status_new_side_meal_id_fkey FOREIGN KEY (new_side_meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_delivery_status_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES auth.users(id),
  CONSTRAINT meal_delivery_status_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meal_delivery_status_second_edit_allowed_by_fkey FOREIGN KEY (second_edit_allowed_by) REFERENCES auth.users(id),
  CONSTRAINT meal_delivery_status_second_edited_by_fkey FOREIGN KEY (second_edited_by) REFERENCES auth.users(id),
  CONSTRAINT meal_delivery_status_new_dessert_meal_id_fkey FOREIGN KEY (new_dessert_meal_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meal_dietary_map (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid NOT NULL,
  dietary_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT meal_dietary_map_pkey PRIMARY KEY (id),
  CONSTRAINT meal_dietary_map_dietary_id_fkey FOREIGN KEY (dietary_id) REFERENCES public.dietary_requirements(id)
);
CREATE TABLE public.meal_discussion_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  discussion_id uuid NOT NULL,
  vote smallint NOT NULL CHECK (vote = ANY (ARRAY['-1'::integer, 1])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_discussion_votes_pkey PRIMARY KEY (id),
  CONSTRAINT meal_discussion_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT meal_discussion_votes_discussion_id_fkey FOREIGN KEY (discussion_id) REFERENCES public.meal_discussions(id)
);
CREATE TABLE public.meal_discussions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid NOT NULL,
  author_id uuid NOT NULL,
  parent_id uuid,
  body text NOT NULL,
  upvotes integer DEFAULT 0,
  downvotes integer DEFAULT 0,
  is_edited boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_discussions_pkey PRIMARY KEY (id),
  CONSTRAINT meal_discussions_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_discussions_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT meal_discussions_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.meal_discussions(id)
);
CREATE TABLE public.meal_ingredients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid NOT NULL,
  ingredient_id uuid NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  quantity_unit text NOT NULL DEFAULT 'g'::text,
  preparation_note text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_ingredients_pkey PRIMARY KEY (id),
  CONSTRAINT meal_ingredients_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id)
);
CREATE TABLE public.meal_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT meal_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT meal_ratings_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meal_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_cycle_id uuid NOT NULL,
  meal_id uuid NOT NULL,
  week_number integer NOT NULL CHECK (week_number >= 1 AND week_number <= 52),
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  meal_type text NOT NULL CHECK (meal_type = ANY (ARRAY['Breakfast'::text, 'Lunch'::text, 'Dinner'::text, 'Supper'::text])),
  slot_kind text NOT NULL DEFAULT 'main'::text CHECK (slot_kind = ANY (ARRAY['main'::text, 'side'::text, 'dessert'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT meal_schedule_meal_cycle_id_fkey FOREIGN KEY (meal_cycle_id) REFERENCES public.meal_cycles(id),
  CONSTRAINT meal_schedule_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meal_special_meals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  date date NOT NULL,
  meal_type text NOT NULL,
  resident_count integer NOT NULL DEFAULT 0,
  special_meal_id uuid NOT NULL,
  special_side_meal_id uuid,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  special_side_meal_ids jsonb,
  special_dessert_ids jsonb,
  special_dessert_id uuid,
  unit_cost numeric,
  subtotal numeric,
  sp_base_unit_cost numeric,
  sp_sides_unit_cost numeric,
  sp_desserts_unit_cost numeric,
  components jsonb,
  CONSTRAINT meal_special_meals_pkey PRIMARY KEY (id),
  CONSTRAINT meal_special_meals_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meal_special_meals_special_meal_id_fkey FOREIGN KEY (special_meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_special_meals_special_side_meal_id_fkey FOREIGN KEY (special_side_meal_id) REFERENCES public.meals(id),
  CONSTRAINT meal_special_meals_special_dessert_id_fkey FOREIGN KEY (special_dessert_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['Breakfast'::text, 'Lunch'::text, 'Supper'::text, 'Special'::text, 'Festive'::text, 'Desserts'::text, 'Side'::text])),
  description text,
  allergens jsonb NOT NULL DEFAULT '[]'::jsonb,
  preparation_instructions text,
  cost_per_person numeric NOT NULL DEFAULT 0,
  nutritional_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  custom_nutrition jsonb NOT NULL DEFAULT '[]'::jsonb,
  care_home_id uuid,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ingredients jsonb NOT NULL DEFAULT '[]'::jsonb,
  resources jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_shared boolean NOT NULL DEFAULT false,
  shared_by_care_home_id uuid,
  shared_at timestamp with time zone,
  shared_by_user_id uuid,
  shared_by_organization_name text,
  created_by_user_id uuid,
  CONSTRAINT meals_pkey PRIMARY KEY (id),
  CONSTRAINT meals_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meals_shared_by_care_home_id_fkey FOREIGN KEY (shared_by_care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT meals_shared_by_user_id_fkey FOREIGN KEY (shared_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT meals_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  logo_url text,
  contact_name text,
  contact_email text,
  contact_phone text,
  billing_email text,
  billing_address text,
  billing_city text,
  billing_postcode text,
  billing_country text DEFAULT 'United Kingdom'::text,
  subscription_plan text DEFAULT 'free'::text CHECK (subscription_plan = ANY (ARRAY['free'::text, 'enterprise'::text])),
  subscription_status text DEFAULT 'active'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'trial'::text, 'suspended'::text, 'cancelled'::text])),
  trial_ends_at timestamp with time zone,
  max_care_homes integer DEFAULT 5,
  max_users integer DEFAULT 50,
  features jsonb DEFAULT '{"help": true, "meals": true, "calendar": true, "analytics": true, "community": true, "dashboard": true, "residents": true, "audit_logs": true, "compliance": true, "admin_users": true, "ingredients": true, "admin_residents": true, "delivery_status": true, "admin_care_homes": true}'::jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.playlist_songs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  playlist_id uuid,
  song_id uuid,
  position integer NOT NULL DEFAULT 0,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT playlist_songs_pkey PRIMARY KEY (id),
  CONSTRAINT playlist_songs_playlist_id_fkey FOREIGN KEY (playlist_id) REFERENCES public.playlists(id),
  CONSTRAINT playlist_songs_song_id_fkey FOREIGN KEY (song_id) REFERENCES public.songs(id)
);
CREATE TABLE public.playlists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  cover_image text,
  is_default boolean DEFAULT false,
  care_home_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT playlists_pkey PRIMARY KEY (id),
  CONSTRAINT playlists_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.residents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  name text NOT NULL,
  date_of_birth date NOT NULL,
  age integer,
  gender text CHECK (gender = ANY (ARRAY['Male'::text, 'Female'::text, 'Other'::text])),
  room_number text NOT NULL,
  admission_date date NOT NULL,
  status text DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Inactive'::text, 'Discharged'::text])),
  emergency_contact_name text,
  emergency_contact_relationship text,
  emergency_contact_phone text,
  emergency_contact_email text,
  dietary_restrictions ARRAY DEFAULT '{}'::text[],
  allergens ARRAY DEFAULT '{}'::text[],
  texture_modification text DEFAULT 'Normal'::text CHECK (texture_modification = ANY (ARRAY['Normal'::text, 'Soft'::text, 'Minced'::text, 'Pureed'::text])),
  medical_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT residents_pkey PRIMARY KEY (id),
  CONSTRAINT residents_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id)
);
CREATE TABLE public.songs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  artist character varying,
  duration integer,
  file_path text NOT NULL,
  file_size integer,
  mime_type character varying,
  uploaded_by uuid,
  care_home_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT songs_pkey PRIMARY KEY (id),
  CONSTRAINT songs_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  name text,
  email text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'Care Home Staff'::text CHECK (role = ANY (ARRAY['Super Admin'::text, 'Organization Admin'::text, 'Care Home Manager'::text, 'Care Home Staff'::text, 'admin'::text, 'staff'::text])),
  facility text,
  phone text,
  status text DEFAULT 'Active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  care_home_id uuid,
  organization_id uuid,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT user_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);