-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE activities.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  category_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  objective text,
  duration_minutes integer NOT NULL DEFAULT 60,
  max_participants integer,
  min_participants integer DEFAULT 1,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'archived'::character varying]::text[])),
  location character varying,
  equipment_required text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activities_category_id_fkey FOREIGN KEY (category_id) REFERENCES activities.activity_categories(id),
  CONSTRAINT activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE activities.activity_attendees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  session_id uuid NOT NULL,
  resident_id uuid NOT NULL,
  attendance_status character varying DEFAULT 'attended'::character varying CHECK (attendance_status::text = ANY (ARRAY['attended'::character varying, 'absent'::character varying, 'cancelled'::character varying, 'not_scheduled'::character varying]::text[])),
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  notes text,
  recorded_at timestamp with time zone DEFAULT now(),
  recorded_by uuid,
  CONSTRAINT activity_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT activity_attendees_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT activity_attendees_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id),
  CONSTRAINT activity_attendees_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_attendees_session_id_fkey FOREIGN KEY (session_id) REFERENCES activities.activity_sessions(id)
);
CREATE TABLE activities.activity_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying,
  record_id uuid,
  action character varying,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_audit_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE activities.activity_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  color_code character varying DEFAULT '#3B82F6'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT activity_categories_pkey PRIMARY KEY (id),
  CONSTRAINT activity_categories_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE activities.activity_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  resident_id uuid NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'on_hold'::character varying, 'completed'::character varying]::text[])),
  enrollment_date date NOT NULL DEFAULT CURRENT_DATE,
  discontinuation_date date,
  reason_for_discontinuation text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT activity_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT activity_enrollments_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_enrollments_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities.activities(id),
  CONSTRAINT activity_enrollments_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT activity_enrollments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE activities.activity_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  session_id uuid,
  description character varying NOT NULL,
  expense_category character varying,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  expense_date date NOT NULL,
  payment_method character varying,
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  submitted_by uuid,
  approved_by uuid,
  approval_date timestamp with time zone,
  notes text,
  receipt_stored boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT activity_expenses_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_expenses_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities.activities(id),
  CONSTRAINT activity_expenses_session_id_fkey FOREIGN KEY (session_id) REFERENCES activities.activity_sessions(id),
  CONSTRAINT activity_expenses_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT activity_expenses_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE activities.activity_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  session_id uuid NOT NULL,
  resident_id uuid,
  staff_member_id uuid,
  engagement_level integer CHECK (engagement_level >= 1 AND engagement_level <= 5),
  enjoyment_rating integer CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  feedback_text text,
  behavioral_observations text,
  recommendations text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT activity_feedback_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_feedback_session_id_fkey FOREIGN KEY (session_id) REFERENCES activities.activity_sessions(id),
  CONSTRAINT activity_feedback_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT activity_feedback_staff_member_id_fkey FOREIGN KEY (staff_member_id) REFERENCES auth.users(id)
);
CREATE TABLE activities.activity_resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  resource_name character varying NOT NULL,
  resource_type character varying,
  quantity_needed integer DEFAULT 1,
  quantity_available integer,
  unit_of_measure character varying,
  reorder_level integer,
  cost_per_unit numeric,
  notes text,
  is_reusable boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_resources_pkey PRIMARY KEY (id),
  CONSTRAINT activity_resources_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_resources_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities.activities(id)
);
CREATE TABLE activities.activity_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 60,
  is_recurring boolean DEFAULT true,
  start_date date,
  end_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT activity_schedules_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_schedules_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities.activities(id)
);
CREATE TABLE activities.activity_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  care_home_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  schedule_id uuid,
  session_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  location character varying,
  facilitator_id uuid,
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  notes text,
  actual_duration_minutes integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT activity_sessions_care_home_id_fkey FOREIGN KEY (care_home_id) REFERENCES public.care_homes(id),
  CONSTRAINT activity_sessions_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities.activities(id),
  CONSTRAINT activity_sessions_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES activities.activity_schedules(id),
  CONSTRAINT activity_sessions_facilitator_id_fkey FOREIGN KEY (facilitator_id) REFERENCES auth.users(id)
);